{{- if and (.Values.ruler.enabled) (.Values.ruler.service.additionalHeadless) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-ruler-headless
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ruler
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.ruler.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.ruler.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: rcp
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: ruler
{{- end }}
