{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if and ($query.grpcTLS.server.secure) (not $query.grpcTLS.server.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" .Values.query.grpcTLS.server.existingSecret "defaultNameSuffix" "query-tls-server" "context" $) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: query
type: Opaque
data:
  tls-cert: {{ $query.grpcTLS.server.cert | b64enc | quote }}
  tls-key: {{ $query.grpcTLS.server.key | b64enc | quote }}
  ca-cert : {{ $query.grpcTLS.server.ca | b64enc | quote }}
{{ end }}
