{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if $query.ingress.enabled }}
{{- range $query.ingress.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-query
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{- end }}
{{- end }}
