kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-rbac-proxy
  namespace: saberkan-thanos-proxy
  labels:
    app: kube-rbac-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-rbac-proxy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-rbac-proxy
    spec:
      restartPolicy: Always
      serviceAccountName: kube-rbac-proxy
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: kube-rbac-proxy
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /etc/kube-rbac-proxy
          terminationMessagePolicy: File
          image: >-
            quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1309762c80489864d7f511a14b3dc2b334ed4cd3be5d0fe364165f2928f04fc2
          args:
            - '--insecure-listen-address=0.0.0.0:8443'
            - '--upstream=http://127.0.0.1:8080/'
            - '--config-file=/etc/kube-rbac-proxy/config.yaml'
            - '--logtostderr=true'
            - '--v=10'
        - name: prom-label-enforcer
          image: 'quay.io/coreos/prom-label-proxy:v0.1.0'
          args:
            - '--insecure-listen-address=127.0.0.1:8080'
            - >-
              --upstream=http://thanos-query.saberkan-thanos-poc.svc.cluster.local:9090/
            - '--label=namespace'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      serviceAccount: kube-rbac-proxy
      volumes:
        - name: config
          configMap:
            name: kube-rbac-proxy
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 2147483647
  progressDeadlineSeconds: 2147483647
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-rbac-proxy
  namespace: saberkan-thanos-proxy
data:
  config.yaml: |+
    authorization:
      resourceAttributes:
        namespace: saberkan-thanos-proxy
        apiVersion: v1
        resource: services
        subresource: proxy
        name: kube-rbac-proxy
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kube-rbac-proxy
  namespace: saberkan-thanos-proxy
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-rbac-proxy
rules:
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-rbac-proxy
subjects:
  - kind: ServiceAccount
    name: kube-rbac-proxy
    namespace: saberkan-thanos-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-rbac-proxy
---
kind: Service
apiVersion: v1
metadata:
  name: kube-rbac-proxy
  namespace: saberkan-thanos-proxy
  labels:
    app: kube-rbac-proxy
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
  selector:
    app: kube-rbac-proxy
  type: ClusterIP
  sessionAffinity: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: thanos-rbac-proxy-insecure
  namespace: saberkan-thanos-proxy
  labels:
    app: kube-rbac-proxy
spec:
  to:
    kind: Service
    name: kube-rbac-proxy
    weight: 100
  port:
    targetPort: https
  wildcardPolicy: None
