{{- if .Values.queryFrontend.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-query-frontend
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.queryFrontend.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.queryFrontend.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- if .Values.queryFrontend.ingress.hostname }}
    - host: {{ .Values.queryFrontend.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.queryFrontend.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.queryFrontend.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-%s"  (include "common.names.fullname" .) "query-frontend") "servicePort" "http" "context" $)  | nindent 14 }}
    {{- end }}
    {{- range .Values.queryFrontend.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-%s"  (include "common.names.fullname" .) "query-frontend") "servicePort" "http" "context" $) | nindent 14 }}
    {{- end }}
  {{- if or .Values.queryFrontend.ingress.tls .Values.queryFrontend.ingress.extraTls .Values.queryFrontend.ingress.hosts }}
  tls:
    {{- if .Values.queryFrontend.ingress.secrets }}
    - hosts:
        - {{ .Values.queryFrontend.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.queryFrontend.ingress.hostname }}
    {{- end }}
    {{- if .Values.queryFrontend.ingress.extraTls }}
    {{- toYaml .Values.queryFrontend.ingress.extraTls | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
