{{- if (include "thanos.receive.createConfigmap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-receive
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: receive
data:
  hashrings.json: |
    {{ .Values.receive.config  | toJson | nindent 4 }}
{{ end }}
