{{- if and .Values.receive.ingress.enabled  .Values.receive.enabled}}
{{- range .Values.receive.ingress.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-receive
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{- end }}
{{- end }}
